"""attendance token value column

Revision ID: 6975c6720347
Revises: 7abc4039822f
Create Date: 2026-06-19 11:14:44.492830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6975c6720347'
down_revision: Union[str, None] = '7abc4039822f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_tokens', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
