"""qr attendance: total_sessions, session status, attendance_tokens

Revision ID: 7abc4039822f
Revises: be3f5d4ddc5f
Create Date: 2026-06-19 11:07:36.010121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abc4039822f'
down_revision: Union[str, None] = 'be3f5d4ddc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendance_tokens_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('scheduled', 'ended', 'cancelled', name='sessionstatus', native_enum=False), nullable=False, server_default='scheduled'))

    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sessions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_column('total_sessions')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('attendance_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_tokens_session_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_tokens_jti'))

    op.drop_table('attendance_tokens')
    # ### end Alembic commands ###
